site_name:  linux-command
pages:    
   - Home: index.md   
   - ab.md
   - accept.md
   - ack.md
   - alias.md
   - apachectl.md
   - apk.md
   - apropos.md
   - apt-get.md
   - aptitude.md
   - apt-key.md
   - apt-sortpkgs.md
   - arch.md
   - arj.md
   - ar.md
   - arpd.md
   - arping.md
   - arp.md
   - arptables.md
   - arpwatch.md
   - as.md
   - at.md
   - atop.md
   - atq.md
   - atrm.md
   - awk.md
   - axel.md
   - badblocks.md
   - basename.md
   - batch.md
   - bc.md
   - bg.md
   - bind.md
   - blkid.md
   - blockdev.md
   - bmodinfo.md
   - builtin.md
   - bunzip2.md
   - bye.md
   - bzcat.md
   - bzcmp.md
   - bzdiff.md
   - bzgrep.md
   - bzip2.md
   - bzip2recover.md
   - bzless.md
   - bzmore.md
   - cal.md
   - cancel.md
   - cat.md
   - cd.md
   - cdrecord.md
   - chage.md
   - chattr.md
   - chcon.md
   - chfn.md
   - chgrp.md
   - chkconfig.md
   - chmod.md
   - chown.md
   - chpasswd.md
   - chroot.md
   - chsh.md
   - cksum.md
   - clear.md
   - clockdiff.md
   - clock.md
   - cmp.md
   - col.md
   - colrm.md
   - command.md
   - comm.md
   - compress.md
   - consoletype.md
   - convertquota.md
   - cpio.md
   - cp.md
   - crontab.md
   - csplit.md
   - cu.md
   - cupsdisable.md
   - cupsenable.md
   - curl.md
   - cut.md
   - date.md
   - dd.md
   - declare.md
   - depmod.md
   - df.md
   - dhclient.md
   - dhcpd.md
   - dhcrelay.md
   - diff3.md
   - diff.md
   - diffstat.md
   - dig.md
   - dircolors.md
   - dirname.md
   - dirs.md
   - dmesg.md
   - dmidecode.md
   - dnf.md
   - dnsdomainname.md
   - domainname.md
   - dos2unix.md
   - dpkg-deb.md
   - dpkg-divert.md
   - dpkg.md
   - dpkg-preconfigure.md
   - dpkg-query.md
   - dpkg-reconfigure.md
   - dpkg-split.md
   - dpkg-statoverride.md
   - dpkg-trigger.md
   - dris.md
   - dstat.md
   - du.md
   - dump.md
   - e2fsck.md
   - e2label.md
   - echo.md
   - ed.md
   - edquota.md
   - egrep.md
   - eject.md
   - elinks.md
   - elm.md
   - emacs.md
   - enable.md
   - env.md
   - ethtool.md
   - exec.md
   - exit.md
   - ex.md
   - expand.md
   - exportfs.md
   - export.md
   - expr.md
   - fc.md
   - fdisk.md
   - fg.md
   - fgrep.md
   - file.md
   - findfs.md
   - find.md
   - finger.md
   - firewall-cmd.md
   - fishshell.md
   - fmt.md
   - fold.md
   - free.md
   - fsck.md
   - ftpcount.md
   - ftp.md
   - ftpshut.md
   - ftptop.md
   - ftpwho.md
   - fuser.md
   - gcc.md
   - gcov.md
   - gdb.md
   - getenforce.md
   - get_module.md
   - getsebool.md
   - git.md
   - gpasswd.md
   - gpm.md
   - grep.md
   - groupadd.md
   - groupdel.md
   - groupmod.md
   - groups.md
   - grpck.md
   - grpconv.md
   - grpunconv.md
   - grub.md
   - gunzip.md
   - gzexe.md
   - gzip.md
   - halt.md
   - hdparm.md
   - head.md
   - help.md
   - hexdump.md
   - history.md
   - hostid.md
   - host.md
   - hostname.md
   - hping3.md
   - htdigest.md
   - htop.md
   - htpasswd.md
   - hwclock.md
   - iconv.md
   - id.md
   - ifcfg.md
   - ifconfig.md
   - ifdown.md
   - ifstat.md
   - iftop.md
   - ifup.md
   - indent.md
   - info.md
   - init.md
   - inotifywait.md
   - insmod.md
   - install.md
   - iostat.md
   - iotop.md
   - ip6tables.md
   - ip6tables-restore.md
   - ip6tables-save.md
   - ipcalc.md
   - ipcrm.md
   - ipcs.md
   - iperf.md
   - ip.md
   - iptables.md
   - iptables-restore.md
   - iptables-save.md
   - iptraf.md
   - iptstate.md
   - ispell.md
   - jed.md
   - jobs.md
   - joe.md
   - join.md
   - jwhois.md
   - kernelversion.md
   - kexec.md
   - killall.md
   - kill.md
   - lastb.md
   - lastlog.md
   - last.md
   - ldconfig.md
   - ldd.md
   - ld.md
   - less.md
   - let.md
   - lftpget.md
   - lftp.md
   - lha.md
   - lilo.md
   - ln.md
   - lnstat.md
   - locate.md
   - logger.md
   - login.md
   - logname.md
   - logout.md
   - logrotate.md
   - logsave.md
   - logwatch.md
   - look.md
   - losetup.md
   - lpadmin.md
   - lpc.md
   - lp.md
   - lpq.md
   - lpr.md
   - lprm.md
   - lpstat.md
   - lsattr.md
   - lsblk.md
   - lsb_release.md
   - lscpu.md
   - ls.md
   - lsmod.md
   - lsof.md
   - lspci.md
   - lsusb.md
   - ltrace.md
   - lvcreate.md
   - lvdisplay.md
   - lvextend.md
   - lvreduce.md
   - lvremove.md
   - lvresize.md
   - lvscan.md
   - lynx.md
   - mail.md
   - mailq.md
   - mailstat.md
   - make.md
   - man.md
   - md5sum.md
   - mesg.md
   - mii-tool.md
   - mkbootdisk.md
   - mkdir.md
   - mke2fs.md
   - mkfs.md
   - mkinitrd.md
   - mkisofs.md
   - mknod.md
   - mkswap.md
   - mktemp.md
   - modprobe.md
   - more.md
   - mount.md
   - mpstat.md
   - mtools.md
   - mv.md
   - mysqladmin.md
   - mysqldump.md
   - mysqlimport.md
   - mysql.md
   - mysqlshow.md
   - named-checkzone.md
   - nano.md
   - ncftp.md
   - nc.md
   - nethogs.md
   - netstat.md
   - newusers.md
   - nfsstat.md
   - ngrep.md
   - nice.md
   - nisdomainname.md
   - nl.md
   - nmap.md
   - nmcli.md
   - nm.md
   - nohup.md
   - nologin.md
   - nslookup.md
   - ntpdate.md
   - ntsysv.md
   - objdump.md
   - od.md
   - openssl.md
   - parted.md
   - partprobe.md
   - passwd.md
   - paste.md
   - patch.md
   - pathchk.md
   - perl.md
   - pfctl.md
   - pgrep.md
   - php.md
   - pico.md
   - pidof.md
   - pigz.md
   - ping.md
   - pkill.md
   - pmap.md
   - popd.md
   - poweroff.md
   - ppp-off.md
   - printf.md
   - pr.md
   - protoize.md
   - ps.md
   - pssh.md
   - pstack.md
   - pstree.md
   - pushd.md
   - pvchange.md
   - pvck.md
   - pvcreate.md
   - pvdisplay.md
   - pv.md
   - pvremove.md
   - pvscan.md
   - pvs.md
   - pwck.md
   - pwconv.md
   - pwd.md
   - pwunconv.md
   - quotacheck.md
   - quota.md
   - quotaoff.md
   - quotaon.md
   - rcconf.md
   - rcp.md
   - readelf.md
   - read.md
   - readonly.md
   - reboot.md
   - reject.md
   - rename.md
   - renice.md
   - repquota.md
   - resize.md
   - restorecon.md
   - restore.md
   - rev.md
   - rexec.md
   - rlogin.md
   - rmdir.md
   - rm.md
   - rmmod.md
   - route.md
   - rpm2cpio.md
   - rpmbuild.md
   - rpmdb.md
   - rpm.md
   - rpmquery.md
   - rpmsign.md
   - rpmverify.md
   - rsh.md
   - rsync.md
   - runlevel.md
   - sar.md
   - scp.md
   - screen.md
   - sed.md
   - seinfo.md
   - semanage.md
   - sendmail.md
   - seq.md
   - service.md
   - sesearch.md
   - setfacl.md
   - set.md
   - setpci.md
   - setsebool.md
   - setsid.md
   - sftp.md
   - sftp-server.md
   - sh.md
   - shopt.md
   - showmount.md
   - shutdown.md
   - skill.md
   - slabtop.md
   - sleep.md
   - slocate.md
   - smbclient.md
   - smbpasswd.md
   - sort.md
   - source.md
   - speedtest-cli.md
   - spell.md
   - split.md
   - squidclient.md
   - squid.md
   - ssh-add.md
   - ssh-agent.md
   - ssh-copy-id.md
   - sshd.md
   - ssh-keygen.md
   - ssh-keyscan.md
   - ssh.md
   - ss.md
   - startx.md
   - stat.md
   - strace.md
   - strings.md
   - stty.md
   - sudo.md
   - su.md
   - sum.md
   - supervisord.md
   - swapoff.md
   - swapon.md
   - sync.md
   - sysctl.md
   - syslog.md
   - systemctl.md
   - systool.md
   - tac.md
   - tailf.md
   - tail.md
   - talk.md
   - tar.md
   - tcpdump.md
   - tcpreplay.md
   - tee.md
   - telint.md
   - telnet.md
   - tempfile.md
   - test.md
   - tftp.md
   - time.md
   - tload.md
   - tmux.md
   - top.md
   - touch.md
   - tput.md
   - tracepath.md
   - traceroute.md
   - trap.md
   - tree.md
   - tr.md
   - tty.md
   - type.md
   - ulimit.md
   - umask.md
   - umount.md
   - unalias.md
   - uname.md
   - unarj.md
   - uncompress.md
   - unexpand.md
   - uniq.md
   - unlink.md
   - unprotoize.md
   - unset.md
   - unzip.md
   - updatedb.md
   - uptime.md
   - useradd.md
   - userdel.md
   - usermod.md
   - usernetctl.md
   - users.md
   - uucico.md
   - uupick.md
   - vdfuse.md
   - vgchange.md
   - vgconvert.md
   - vgcreate.md
   - vgdisplay.md
   - vgextend.md
   - vgreduce.md
   - vgremove.md
   - vgrename.md
   - vgscan.md
   - vi.md
   - vmstat.md
   - volname.md
   - wait.md
   - wall.md
   - watch.md
   - wc.md
   - wget.md
   - whatis.md
   - whereis.md
   - which.md
   - whoami.md
   - who.md
   - w.md
   - write.md
   - xargs.md
   - xauth.md
   - xclip.md
   - xhost.md
   - xinit.md
   - xlsatoms.md
   - xlsclients.md
   - xlsfonts.md
   - xset.md
   - xz.md
   - yes.md
   - ypdomainname.md
   - yum.md
   - zcat.md
   - zfore.md
   - zipinfo.md
   - zip.md
   - zipsplit.md
   - znew.md
   - About: about.md
theme: readthedocs 
